"""Standard-library-only Judge preflight; call before simulator imports."""
from __future__ import annotations
import base64, csv, hashlib, importlib.metadata, json, os, pathlib, re, stat, struct, subprocess, sys, tempfile

TESTS=pathlib.Path("/tests"); WORK=pathlib.Path("/workspace")
LOCK_LINE=re.compile(r"^([A-Za-z0-9_.-]+)(?:\[[^]]+\])?==([^;\s]+)$")
class CandidateProblem(Exception):
    def __init__(self,code,field,condition,expected,actual,hint): self.code=code; self.field=field; self.condition=condition; self.expected=expected; self.actual=actual; self.hint=hint
    def envelope(self): return {"status":"candidate_invalid","code":self.code,"path":self.field if self.field.startswith("/workspace/") else "/workspace/reward.json","field":self.field,"condition":self.condition,"expected":self.expected,"actual":self.actual,"hint":self.hint}
def bad(code,field,condition,expected,actual,hint): raise CandidateProblem(code,field,condition,expected,actual,hint)
def sha(path):
    h=hashlib.sha256()
    with open(path,"rb") as stream:
        while chunk:=stream.read(1024*1024): h.update(chunk)
    return h.hexdigest()
def command(*args):
    done=subprocess.run(args,stdin=subprocess.DEVNULL,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,timeout=60,check=False,env={"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG":"C.UTF-8"})
    if done.returncode: raise RuntimeError(f"fixed-runtime preflight command failed: {args[0]}: {done.stderr.strip()}")
    return done.stdout.strip()
def verify_git(path,commit):
    if command("git","-C",path,"rev-parse","HEAD")!=commit: raise RuntimeError(f"immutable source revision mismatch: {path}")
    status=command("git","-C",path,"status","--porcelain=v1","--untracked-files=all","--ignored")
    if status: raise RuntimeError(f"immutable source tree is not pristine: {path}")
def verify_record(package):
    dist=importlib.metadata.distribution(package); records=[p for p in (dist.files or []) if len(pathlib.PurePosixPath(str(p)).parts)==2 and str(p).endswith(".dist-info/RECORD")]
    if len(records)!=1: raise RuntimeError(f"missing wheel RECORD: {package}")
    record=dist.locate_file(records[0])
    with open(record,newline="",encoding="utf-8") as stream:
        for name,digest,size in csv.reader(stream):
            if not digest or not digest.startswith("sha256="): continue
            if name.endswith(".pyc"): continue  # bytecode caches are regenerated by the installer; sources are verified
            target=pathlib.Path(dist.locate_file(name)).resolve()
            if not target.is_file(): raise RuntimeError(f"wheel file missing: {package}")
            expected=base64.urlsafe_b64decode(digest[7:]+"="*((4-len(digest[7:])%4)%4)).hex()
            if sha(target)!=expected: raise RuntimeError(f"wheel RECORD mismatch: {package}")
def locked_packages(cfg):
    lock=pathlib.Path("/opt/peginsert_build/requirements.lock")
    if sha(lock)!=cfg["requirements_lock_sha256"]: raise RuntimeError("task dependency lock identity mismatch")
    expected=dict(cfg["local_packages"]); canonical={re.sub(r"[-_.]+","-",name).lower() for name in expected}
    for raw in lock.read_text(encoding="utf-8").splitlines():
        line=raw.strip()
        if not line or line.startswith("#"): continue
        match=LOCK_LINE.fullmatch(line)
        if match is None: raise RuntimeError(f"non-exact task dependency: {line}")
        name,version=match.groups(); normalized=re.sub(r"[-_.]+","-",name).lower()
        if normalized in canonical: raise RuntimeError(f"duplicate task dependency: {name}")
        canonical.add(normalized); expected[name]=version
    manifest=json.loads(pathlib.Path("/opt/peginsert_public/runtime_manifest.json").read_text(encoding="utf-8"))
    recorded=manifest.get("packages",{})
    if manifest.get("schema_version")!=1 or manifest.get("python")!="3.11" or manifest.get("platform")!="linux" or manifest.get("lock_sha256")!=cfg["requirements_lock_sha256"]: raise RuntimeError("runtime manifest identity mismatch")
    if set(recorded)!=set(expected) or any(recorded[name].get("version")!=version for name,version in expected.items()): raise RuntimeError("runtime manifest package closure mismatch")
    return expected
EXTRA_CANDIDATES=("reward_1.json",)
def candidate_files():
    """Ordered public candidate paths: the primary recipe plus one optional extra under /workspace/candidates."""
    entries={p.name:p for p in WORK.iterdir()}
    if not {"reward.json","research"}<=set(entries) or not set(entries)<={"reward.json","research","candidates"}: bad("workspace_scope","$","root_entries",["research","reward.json","candidates (optional)"],sorted(entries),"Keep only the candidate file, the optional candidates directory, and the Work-only research directory at workspace root.")
    if entries["research"].is_symlink() or not entries["research"].is_dir(): bad("research_type","/workspace/research","real_directory","directory","other","Replace research with a real directory; Judge ignores its contents.")
    files=[entries["reward.json"]]
    if "candidates" in entries:
        extra=entries["candidates"]
        if extra.is_symlink() or not extra.is_dir(): bad("candidates_type","/workspace/candidates","real_directory","directory","other","Replace candidates with a real directory holding reward_1.json.")
        names=sorted(p.name for p in extra.iterdir())
        if not names or any(name not in EXTRA_CANDIDATES for name in names): bad("candidates_scope","/workspace/candidates","entries",list(EXTRA_CANDIDATES),names,"Keep only reward_1.json under candidates.")
        if names!=list(EXTRA_CANDIDATES[:len(names)]): bad("candidates_order","/workspace/candidates","contiguous_names",list(EXTRA_CANDIDATES[:len(names)]),names,"Number extra candidates contiguously from reward_1.json.")
        files+=[extra/name for name in names]
    return files
def candidate_copy(source,root):
    public=str(source)
    info=source.lstat()
    if not stat.S_ISREG(info.st_mode): bad("candidate_type",public,"regular_file","regular file","other","Replace the candidate path with one closed regular file.")
    if info.st_size>65536: bad("candidate_size",public,"maximum_bytes",65536,info.st_size,"Reduce the recipe size.")
    target=root/source.name
    src=os.open(source,os.O_RDONLY|getattr(os,"O_NOFOLLOW",0)); dst=os.open(target,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
    try:
        copied=0
        while True:
            chunk=os.read(src,65536)
            if not chunk: break
            copied+=len(chunk)
            if copied>65536: bad("candidate_changed",public,"stable_read",info.st_size,copied,"Close and flush the file before submission.")
            view=memoryview(chunk)
            while view: view=view[os.write(dst,view):]
        os.fsync(dst)
    finally: os.close(src); os.close(dst)
    if copied!=info.st_size: bad("candidate_changed",public,"stable_read",info.st_size,copied,"Close and flush the file before submission.")
    return target
def candidate_copies():
    """Stage every candidate into its own private scratch directory; returns [(public_path, staged_path)]."""
    staged=[]
    for source in candidate_files():
        root=pathlib.Path(tempfile.mkdtemp(prefix="peginsert-judge-",dir="/tmp")); os.chmod(root,0o700)
        staged.append((str(source),candidate_copy(source,root)))
    return staged
def verify_assets():
    root=pathlib.Path("/opt/peginsert_assets"); manifest=json.loads((root/"manifest.json").read_text())
    if manifest.get("schema_version")!=2 or manifest.get("closure_verified") is not True or sorted(manifest.get("roots",{}))!=sorted(CONFIG["asset_roots"]): raise RuntimeError("offline asset manifest is incomplete")
    listed={item.get("path") for item in manifest.get("files",[])}
    actual={str(path.relative_to(root)) for path in root.rglob("*") if path.is_file() and path!=root/"manifest.json"}
    if None in listed or listed!=actual: raise RuntimeError("offline asset closure does not match its manifest")
    for item in manifest.get("files",[]):
        path=(root/item["path"]).resolve()
        if not path.is_relative_to(root): raise RuntimeError("offline asset path escaped its root")
        if not path.is_file() or path.stat().st_size!=item["size"] or sha(path)!=item["sha256"]: raise RuntimeError("offline asset identity mismatch")
def verify_reference(cfg):
    root=pathlib.Path("/opt/peginsert_reference/converted"); provenance=json.loads((root/"provenance.json").read_text()); source=provenance.get("source",{}); derived=provenance.get("derived",{}); policy=root/"policy.safetensors"
    if source!={"size":cfg["checkpoint_size"],"sha256":cfg["checkpoint_sha256"]}: raise RuntimeError("reference source provenance mismatch")
    if derived.get("tensor_count")!=28 or not policy.is_file() or policy.stat().st_size!=derived.get("size") or sha(policy)!=derived.get("sha256"): raise RuntimeError("derived reference identity mismatch")
    with open(policy,"rb") as stream:
        length_raw=stream.read(8)
        if len(length_raw)!=8: raise RuntimeError("truncated Safetensors header")
        length=struct.unpack("<Q",length_raw)[0]
        if length>1_048_576 or length>policy.stat().st_size-8: raise RuntimeError("invalid Safetensors header length")
        header=json.loads(stream.read(length))
    tensors={k:v for k,v in header.items() if k!="__metadata__"}; inventory=derived.get("inventory",{})
    if len(tensors)!=28 or sum(v.get("dtype")=="F64" for v in tensors.values())!=6: raise RuntimeError("reference tensor header inventory mismatch")
    if set(inventory)!=set(tensors): raise RuntimeError("reference tensor provenance names mismatch")
    spans=[]
    for name,item in tensors.items():
        if not isinstance(name,str) or item.get("dtype") not in {"F32","F64"} or not isinstance(item.get("shape"),list) or any(type(x) is not int or x<0 for x in item["shape"]): raise RuntimeError("invalid Safetensors tensor metadata")
        begin,end=item.get("data_offsets",[None,None])
        if not isinstance(begin,int) or not isinstance(end,int) or begin<0 or end<begin: raise RuntimeError("invalid Safetensors byte span")
        elements=1
        for extent in item["shape"]: elements*=extent
        expected={"shape":item["shape"],"dtype":"torch.float64" if item["dtype"]=="F64" else "torch.float32","bytes":elements*(8 if item["dtype"]=="F64" else 4)}
        if inventory[name]!=expected or end-begin!=expected["bytes"]: raise RuntimeError("reference tensor provenance mismatch")
        spans.append((begin,end))
    spans.sort()
    if spans[0][0]!=0 or any(left[1]!=right[0] for left,right in zip(spans,spans[1:])) or spans[-1][1]!=policy.stat().st_size-8-length: raise RuntimeError("noncanonical Safetensors byte spans")
def preflight():
    global CONFIG
    cfg=json.loads((TESTS/"fixed_config.json").read_text())
    CONFIG=cfg
    for key in ("PYTHONPATH","PYTHONHOME","PYTHONSTARTUP","PYTHONINSPECT","PYTHONUSERBASE"): os.environ.pop(key,None)
    os.environ.update({"PYTHONNOUSERSITE":"1","PYTHONDONTWRITEBYTECODE":"1","PIP_CONFIG_FILE":"/dev/null","WANDB_MODE":"disabled","HF_HUB_OFFLINE":"1","TRANSFORMERS_OFFLINE":"1"})
    sys.path[:]=[entry for entry in sys.path if entry and not pathlib.Path(entry).resolve().is_relative_to(WORK)]
    staged=candidate_copies()
    verify_git("/opt/isaaclab",cfg["isaaclab_commit"]); verify_git("/opt/rl_games",cfg["rl_games_commit"])
    for package,version in locked_packages(cfg).items():
        if importlib.metadata.version(package)!=version: raise RuntimeError(f"fixed package version mismatch: {package}")
        verify_record(package)
    for path,digest in cfg["public_files"].items():
        if sha(path)!=digest: raise RuntimeError(f"task-owned runtime byte mismatch: {path}")
    verify_assets(); verify_reference(cfg)
    return cfg,staged
